version: "3.9"
services:

#  ocremix-api:
##    image: ocremix-api:latest
#    build: ../ocremix-api/
#    depends_on:
#      - ocremix-mongo-db
#    ports:
#      - "5000:5000"
#    environment:
#      - MONGO_HOST=ocremix-mongo-db
#      - MONGO_PORT=27017
#      - MONGO_DATABASE=ocremix
#    command: ["python", "api.py"]

  ocremix-mongo-db:
    image: mongo:latest
    ports:
     - 27017:27017

  ocremix-consumer:
    build: ../ocremix-consumer
    depends_on:
      - ocremix-mongo-db
      - localstack
    environment:
      - MONGO_HOST=ocremix-mongo-db
      - MONGO_PORT=27017
      - MONGO_DATABASE=ocremix
      - ENV=dev
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=us-east-1
    command: ["python", "-m", "main.py"]

  ocremix-spider:
    build: ../ocremix-spider/
    volumes:
      - ocremix-html:/tmp/ocremix
    depends_on:
      - localstack
    environment:
      - ENV=dev
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=us-east-1
    command: ["scrapy", "crawl", "ocremix"]

  ocremix-html-parser:
    build: ../ocremix-html-parser/
    volumes:
      - ocremix-html:/tmp/ocremix
    environment:
      - ENV=dev
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - localstack
    command: ["python", "main.py"]

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=0
    volumes:
      - "./init:/docker-entrypoint-initaws.d"
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

  logger:
    image: sebp/elk
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044
      - 5959:5959/udp
    volumes:
      - type: bind
        source: "./init/03-logstash-tcp-input.conf"
        target: "/etc/logstash/conf.d/03-logstash-tcp-input.conf"


volumes:
  ocremix-html:
